language: node_js

node_js:
  - "v10.13.0"

script:
  - npx depcheck .
  - npm run build
  - npx eslint src/components
  - npx eslint src/constants
  - npx eslint src/variables
  - npx eslint src/views